### PR TITLE
Started with translation to nl_nl

### PR DESCRIPTION
**Pull request by Vincent-Br**

### CODE REVIEW

**Comment by Kruemmelspalter** [comment]
I would only pull if it is (nearly) complete but not for each of your commits

**Comment by JustDoom** [comment]
If you work on this a bit more I'll add it

**Comment by Kruemmelspalter** [comment]
Work on it in your branch and then make a new PR, I'll close this one for now

**Comment by JustDoom** [comment]
are you still working on this @Vincent-Br ?

**Pull request closed without merging**
