### PR TITLE
Added Yatopia and Magma

### PR DESCRIPTION
**Pull request by ElMoha943**
# Description
Added Yatopia to server jars and Magma to mods + plugin server jar
Also touched some estetic aspects, feel free of editing, changing. PLEASE review for grammar/spelling errors as im not native english speaker thanx you.

### CODE REVIEW

**Comment by JustDoom** [comment]
another pr has conflicting files sorry

**Comment by Silverarmor** [comment]
> another pr has conflicting files sorry

what? The whole point of Git is for users to collaborate together. Conflicts are normal and fixable. If you don't accept a PR **just** because there are conflicts, you literally break the whole point of Git.

**Comment by JustDoom** [comment]
> > another pr has conflicting files sorry
> 
> what? The whole point of Git is for users to collaborate together. Conflicts are normal and fixable. If you don't accept a PR **just** because there are conflicts, you literally break the whole point of Git.
> 
> @JustDoom

true, ill try to fix it

**Comment by Silverarmor** [comment]
## Please update your branch from master & make changes there. Open a new PR when done.

**Pull request closed without merging**
