### PR TITLE
Kubernetes configuration

### PR DESCRIPTION
**Pull request by mbround18**
# Description

- Added advanced deployment for kubernetes
- Added more information for docker information
- Cleaned up a few files. 

## Checklist

- [x] My contributions follows the style guidelines of this project
- [x] I have performed a self-review of my own contributions (checked for spelling errors, proper linking, etc)
- [x] I have run linting on my branch before submitting the PR

### CODE REVIEW

**Comment by JustDoom** [comment]
im always breaking your pr sorry

**Comment by mbround18** [comment]
Rip lol I'll fix it in a bit

**Comment by mbround18** [comment]
@JustDoom fixed

**Review by JustDoom — APPROVED** [review]

**Comment by JustDoom** [comment]
@mbround18 whats Kubernetes btw?

**Pull request merged**
