### PR TITLE
Made some changes

### PR DESCRIPTION
**Pull request by ElMoha943**
Added some things, feel free to delete/change what you dont like. I believe most server owners wont be using fabric for production servers, fabric is more oriented to tech players and tech servers. Most people will have the best experience running papermc or other spigot fork as they have a HUGE amount of plugins and documentation.

### CODE REVIEW

**Review by JustDoom — APPROVED** [review]

**Comment by Silverarmor** [comment]
i STRONGLY disagree with this. We should still provide descriptions about FabricMC.
Who are we to decide what a server owner would want to use?

**Comment by ElMoha943** [comment]
I didnt remove the fabric info tho, just added things didnt delete anything

**Comment by Silverarmor** [comment]
No one plays on Minecraft 1.6.X

Thats 7 years old matey...

**Comment by Silverarmor** [comment]
The PR wasnt reviewed properly, and errors slipped through the cracks. I elect that we should revert the PR and fix the problems.

**Comment by ElMoha943** [comment]
its clear i ment 1.16.X dude im not the only one with grammar mistakes here

**Comment by Silverarmor** [comment]
But why should simple errors like that be in the final product?

**Comment by ElMoha943** [comment]
for the same reason there were already mistakes in the final product, because noone saw it, you could fix it instead of complaining

**Comment by Silverarmor** [comment]
what do you think im doing smh lmao.
I'm reverting your changes & will fix them in a patch.

**Comment by ElMoha943** [comment]
Someone didnt have his nap today god dammit

**Comment by Silverarmor** [comment]
image


also did u just assume my gender smh

**Comment by ElMoha943** [comment]
na i just assumed you are a dickhead, not gonna work on this anymore

**Comment by Silverarmor** [comment]
now thats the real oof

**Pull request merged**
