### PR TITLE
Remote server management—removed table of contents

### PR DESCRIPTION
**Pull request by TheKingElessar**
# Description

Removed the table of contents.

## Checklist

- [X] My contributions follows the style guidelines of this project
- [x] I have performed a self-review of my own contributions (checked for spelling errors, proper linking, etc)
- [X] I have run linting on my branch before submitting the PR

### CODE REVIEW

**Review by Silverarmor — CHANGES_REQUESTED** [review]
1. Please add alt-text on all images you have uploaded
2. Please upload images to the `/IMAGES/` folder & do NOT use imgur links.

**Comment by Silverarmor** [comment]
Additionally, please update your branch from master & resolve conflicts.

**Comment by Silverarmor** [comment]
Sorry - I just realised I made a mistake when reviewing the commit history, since your branch `TheKingElessar:remote-server-management` is not up to date.

Above mentioned action points still need to be done before this PR will be merged. The file `tutorials/en_us/REMOTE_SERVER_MANAGEMENT.md` is not up to our standards & [contributring guidelines](https://github.com/Anything-Minecraft-Team/anything-minecraft/blob/main/CONTRIBUTING.md)

**Comment by Silverarmor** [comment]
@TheKingElessar  Have you had the chance to review this?

**Comment by Lezurex** [comment]
This PR is fairly outdated. There were many changes in the past few months.

For example, the file path is really not up-to-date. I suggest redoing this (including the requested improvements) in a new branch an PR.

**Pull request closed without merging**
