### PR TITLE
Added FAWE tutorial and images

### PR DESCRIPTION
**Pull request by Kruemmelspalter**
# Description

I added a tutorial for installing and using FAWE

## Checklist

- [x] My contributions follows the style guidelines of this project
- [x] I have performed a self-review of my own contributions (checked for spelling errors, proper linking, etc)
- [x] I have run linting on my branch before submitting the PR

### CODE REVIEW

**Comment by JustDoom** [comment]
fawe is actually bad and can cause world corruption apparently

**Comment by JustDoom** [comment]
i just found this info

"FAWE asyncs things that shouldnt be async, and then flat out skips other parts of the process to speed it up. FAWE gets is speed from skipping important tasks needed for a stable experience. thats the entire reason it broke on starlight; it skips the lighting task, and starlight only runs the lighting task once, not thousands like vanilla's. Starlight had to remove a lot of its own optimizations because people on FAWE were complaining about the plugin not working with starlight.

Paper even considered blacklisting the plugin from even loading at one point, since many of the bugs reported to Paper were caused by FAWE corruptions. They decided it was best not to intervene and just let people break their stuff. At least then they couldn't be labeled the bad guys and could finger point at FAWE.

There is a reason Worldedit hasn't made anything "async". FAWE is known to corrupt worlds. I strongly recommend using the regular WE and just limiting your tasks to what can be handled which is already quite large because of Worldedit's recent major optimizations."

**Review by Silverarmor — APPROVED** [review]
Looks good - Is good to merge.

**Comment by JustDoom** [comment]
> Looks good - Is good to merge.

theres lots of problems with this plugin so idk if we should add it

**Comment by JustDoom** [comment]
ill just add a big warning

**Pull request merged**
