### PR TITLE
Create HOSTING_PROVIDERS.md

### PR DESCRIPTION
**Pull request by JustDoom**
# Description

Adds a list of hosting providers I have found. both good and bad

## Checklist

- [x] My contributions follows the style guidelines of this project
- [x] I have performed a self-review of my own contributions (checked for spelling errors, proper linking, etc)
- [x] I have run linting on my branch before submitting the PR

### CODE REVIEW

**Comment by JustDoom** [comment]
wait, ill fix file name

**Review by Silverarmor — COMMENTED** [review]
I don't think this file is a good idea.
We should pick the top 5-10, and recommend those. Possibly a "full list" can be provided at the bottom of that file. Dumping this information to a reader serves no purpose, and would only serve to confuse them.

**Comment by JustDoom** [comment]
> I don't think this file is a good idea.
> We should pick the top 5-10, and recommend those. Possibly a "full list" can be provided at the bottom of that file. Dumping this information to a reader serves no purpose, and would only serve to confuse them.

ill pick the top 5-10 ones then have them all at the bottom

**Comment by JustDoom** [comment]
better?

**Comment by ElMoha943** [comment]
> ill pick the top 5-10 ones then have them all at the bottom
How do you determine wich are the top ones other than opinion/personal experience?

also here are some more hostings if you want to add to the list:
humbleservers.com
serverminer.com

**Comment by SidhantUnnithan** [comment]
> > ill pick the top 5-10 ones then have them all at the bottom
> 
> How do you determine wich are the top ones other than opinion/personal experience?

How is anything rated in this world? Numbers. Usage. How many people actually like it? The more it has going for itself, the higher it will be ranked.

**Comment by JustDoom** [comment]
> > ill pick the top 5-10 ones then have them all at the bottom
> 
> How do you determine wich are the top ones other than opinion/personal experience?
> 
> also here are some more hostings if you want to add to the list:
> humbleservers.com
> serverminer.com

mostly ratings by people that use it

**Review by Silverarmor — APPROVED** [review]

**Pull request merged**
