### PR TITLE
Create Changing Server settings

### PR DESCRIPTION
**Pull request by Vincent-Br**
Added a tutorial to change MOTD, playercount and more

### CODE REVIEW

**Comment by Kruemmelspalter** [comment]
Maybe include a link to the server properties page (not in main, But in a PR)

**Comment by funnyboy-roks** [comment]
I see that this file doesn't have the `.md` extension.  It needs that in order for GitHub to recognise it as a markdown file.  

You should also add some line breaks where they're necessary, because at the moment, it'll show something similar to this:

Preview

**Comment by Vincent-Br** [comment]
Yeah i saw that when i already created the pull request

**Comment by JustDoom** [comment]
Please change this to an md file then I'll merge

**Review by JustDoom — APPROVED** [review]

**Pull request merged**
