### PR TITLE
Added running server in the background

### PR DESCRIPTION
**Pull request by SidhantUnnithan**
List of changes - 
- Added running it in the background using `tmux`
- Fixed linting

### CODE REVIEW

**Comment by Kruemmelspalter** [comment]
We already have the service guide. I think two guides for background are too much

**Comment by SidhantUnnithan** [comment]
@Kruemmelspalter Service guide is very different from using tmux. Running Minecraft on a tmux session allows easy attaching to and detaching from the server console. I think this addition is necessary since this guide is not only for hardcore server administrators. It is just as relevant for private parties/minecraft enhusiasts and running it as a service is not optimal for people looking to have fun with their friends.

**Comment by Kruemmelspalter** [comment]
Ok I would maybe do
```
### Setup for Server
[differeneces between tmux and service]
#### tmux Setup
[...]
#### service Setup
[...]
```
so it's more organized

**Comment by SidhantUnnithan** [comment]
Agreed and Added

**Review by Kruemmelspalter — APPROVED** [review]

**Pull request merged**
